// ============================================================
// Aven Module 1 — Core Types
// Every type used across M1 lives here.
// ============================================================

export type SourceCategory =
  | 'classifieds'
  | 'social'
  | 'dealer'
  | 'remarketing'
  | 'fleet'
  | 'auction';

export type RawContentType = 'html' | 'json' | 'xml';

export type RotationStrategy = 'PER_REQUEST' | 'PER_SESSION' | 'PER_RUN';

export type HealthStatus = 'OK' | 'DEGRADED' | 'FAILED';

// ────────────────────────────────────────────────────────────
// RawPayload — the data contract between M1 and M2.
// Every item pushed to the Redis ingestion queue must conform.
// Fields must never be omitted; use null if unknown.
// ────────────────────────────────────────────────────────────
export interface RawPayload {
  /** UUID v4. Generated by the connector at push time. */
  payload_id: string;
  /** Connector identifier e.g. 'kijiji-ca'. Immutable per connector. */
  source_id: string;
  source_category: SourceCategory;
  /** Canonical URL of the listing on the source platform. Dedup key. */
  listing_url: string;
  /** ISO 8601 UTC — when the payload was collected (not processed). */
  scrape_timestamp: string;
  /** Semver of the connector that collected this payload. */
  connector_version: string;
  /** Full raw HTML or JSON — untruncated, unmodified. */
  raw_content: string;
  raw_content_type: RawContentType;
  /** Image URLs found in the listing. Empty array (not null) if none. */
  listing_images: string[];
  /** e.g. 'ON-GTA'. Used for regional search indexing. */
  geo_region: string;
  /** UUID v4 shared across all payloads in one scheduler invocation. */
  scrape_run_id: string;
  /** HTTP status of the response that returned this content. */
  http_status: number;
  proxy_used: boolean;
  requires_auth: boolean;
  /** Connector-level hint. null = let M2 decide. */
  is_dealer_listing: boolean | null;
}

// ────────────────────────────────────────────────────────────
// SourceConnector — the interface every connector must implement.
// ────────────────────────────────────────────────────────────
export interface ScrapeConfig {
  runId: string;
  geoRegion: string;
  proxyConfig?: ProxyConfig;
}

export interface HealthResult {
  status: HealthStatus;
  reason?: string;
  timestamp: string;
}

export interface SourceConnector {
  readonly source_id: string;
  readonly source_name: string;
  readonly connector_version: string;
  readonly category: SourceCategory;

  healthCheck(): Promise<HealthResult>;
  /** Yields RawPayload objects one at a time. Caller pushes each to the queue. */
  scrape(config: ScrapeConfig): AsyncGenerator<RawPayload>;
  /** Returns all listing URLs found in one full run (used for testing/auditing). */
  getListingUrls(): Promise<string[]>;

  // Optional — required for JS-rendering connectors
  initBrowser?(proxyConfig: ProxyConfig): Promise<void>;
  closeBrowser?(): Promise<void>;
}

// ────────────────────────────────────────────────────────────
// ProxyConfig — passed to connectors by the Proxy Manager (M1b)
// ────────────────────────────────────────────────────────────
export interface ProxyConfig {
  host: string;
  port: number;
  username: string;
  password: string;
  provider: 'brightdata' | 'oxylabs' | 'none';
}

// ────────────────────────────────────────────────────────────
// ConnectorConfig — stored in Postgres connector_configs table.
// Connectors read this at startup and on every scheduled run.
// ────────────────────────────────────────────────────────────
export interface ConnectorConfig {
  connector_id: string;
  enabled: boolean;
  // Standard cron e.g. "0 */6 * * *" (every 6 hours)
  schedule_cron: string;
  /** Override schedule during peak hours (7am–11pm ET) */
  peak_schedule_cron?: string;
  /** Regions to scrape. ['ON-GTA'] for MVP. */
  geographic_scope: string[];
  vehicle_categories: string[];
  /** Hard cap on listings collected per run to prevent runaway scrapes. */
  max_listings_per_run: number;
  /** [min, max] milliseconds — randomised per request using crypto RNG. */
  request_delay_ms: [number, number];
  max_retries: number;
  timeout_ms: number;
  /** Max result pages to traverse per run. Prevents unbounded crawls. */
  pagination_depth: number;
  /** CSS selectors for HTML connectors. Stored per-connector version. */
  selectors?: Record<string, string>;
  proxy_pool_id: 'brightdata-residential-ca' | 'oxylabs-residential-ca' | 'none';
  stealth_mode: boolean;
  /** Percentage drop in listing count that triggers an M1d alert. Default 20. */
  alert_threshold_pct: number;
}
